name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUST_VERSION: 1.82.0
  SOLANA_VERSION: 2.1.0
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_SIZE: 2G

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy, rust-analyzer

      - name: Install libudev-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Build Solana Program
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          cargo build-sbf --features=test-owner

      - name: Run Rust Tests
        run: cargo test -- --nocapture
